server:
  port: 8083

logging:
  level:
    com:
      example:
        securitybasicflow:
          security: debug

spring:
  application:
    name: security-flow-study
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      password: 1234
